# Generated by Django 4.0.3 on 2022-03-29 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('ico', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12, verbose_name='权限名称')),
                ('url', models.CharField(max_length=100, verbose_name='权限路径')),
                ('ico', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标路径')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='权重')),
                ('is_menu', models.BooleanField(default=False, verbose_name='是否为菜单')),
                ('url_name', models.CharField(max_length=20, unique=True, verbose_name='别称')),
                ('menu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.menu')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.permission', verbose_name='父级菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=20, verbose_name='角色名称')),
                ('permissions', models.ManyToManyField(to='user.permission')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=12, verbose_name='用户名')),
                ('tname', models.CharField(max_length=20, verbose_name='姓名')),
                ('pword', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('mobile', models.CharField(max_length=12, verbose_name='手机号')),
                ('isactive', models.BooleanField(default=True, verbose_name='用户状态')),
                ('roles', models.ManyToManyField(to='user.role', verbose_name='角色')),
            ],
        ),
    ]
