# Generated by Django 4.0.3 on 2022-03-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='别称'),
        ),
    ]
