# Generated by Django 4.0.3 on 2022-03-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_permission_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='别称'),
        ),
    ]
